- hosts: terraform-ansible
  tasks:
  - name: Criando Arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Feito com Terraform & Ansible 2</h1>
  - name: Criando Servidor
    shell: "sudo nohup busybox httpd -f -p 80 &"