- hosts: terraform-ansible
  become: yes
  tasks:
  - name: Criando Arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Feito com Terraform & Ansible 2</h1>
  - name: Criando Servidor
    shell: "nohup busybox httpd -f -p 80 &"
  - name: Instalando novos pacotes
    apt:
        name:
        - python3
        - virtualenv
        update_cache: yes
  - name: Instalando Depedencias do Django & Djangorestframework
    pip:
      virtualenv: /home/ubuntu/tcc/virtualenv
      name:
      - django
      - djangorestframework
  - name: iniciando o projeto
    shell: '. /home/ubuntu/tcc/virtualenv/bin/activate; django-admin startproject setup /home/ubuntu/tcc'
  - name: Alterando os hosts do settings
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regex: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
  - name: iniciando o serivdor django
    shell: 'cd /home/ubuntu/tcc;. virtualenv/bin/activate; python manage.py runserver 0.0.0.0:8000'